Data collection
MadelineKelly196/Spectrofy pull request #4
Opened 2023-12-19 01:53 UTC by octodoge

* Notebook to create the dataset
* First version of the dataset (~1000 tracks)
* Notes about usage of `conda` and Git LFS (how I used them, but we can discuss about it)
* Python class to use the dataset with PyTorch (both for genre and danceability)
    * If genre, should works as it is with the code of Marta in substitution of the class she used (but not tested with her code yet)
* `git push --force` instead of `git push` in `README.md` when talking about the rebase (not tested without `--force` actually but shouldn't work)

2023-12-19 14:18 UTC, octodoge commented
@MadelineKelly196 please make sure that we cannot force pushing in the main branch:

*Settings* -> *Branches* -> in the rules for `main`, *Allow force pushes* should **NOT** be ticked

2023-12-19 17:10 UTC, octodoge commented
@15Max FYI

To test the dataset with the code of Marta I had to do the following modifications to `environment.yml`:

Original:
```
name: spectrofy
dependencies:
  - jupyter
  - pandas
  - matplotlib
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly
  - pip
  - pip:
      - spotipy
      - librosa
      - streamlit
```

Modified:
```
name: spectrofy
dependencies:
  - jupyter
  - pandas
  - matplotlib!=3.8
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::cpuonly
  - seaborn
  - pip
  - pip:
      - spotipy
      - librosa
      - streamlit
```

That is:
* I excluded version 3.8 (latest available for my system at time of writing) for `matplotlib` because [bugged](https://github.com/librosa/librosa/issues/1763)
* I added `seaborn`

But I didn't keep the changes because currently not needed for this project

2023-12-20 01:09 UTC, MadelineKelly196 commented
> @MadelineKelly196 please make sure that we cannot force pushing in the main branch:
> 
> _Settings_ -> _Branches_ -> in the rules for `main`, _Allow force pushes_ should **NOT** be ticked

@octodoge - I verified that force pushing is NOT allowed on the main branch, within the ruleset specified.

2023-12-20 01:34 UTC, MadelineKelly196 requested changes
Overall things look good to me!
Let me know if you'd like to meet and chat about my comments. Otherwise, when you get a chance to modify the code block 6 section, just ping me for re-review.

2023-12-20 01:34 UTC, MadelineKelly196 commented on README.md
@octodoge, can you explain more here about why you want to switch from "git push" to "git push --force-with-lease"?

2023-12-20 01:34 UTC, MadelineKelly196 commented on data_collection.ipynb
Could you pop out the functions in code block 6 into a separate file so that I can also use them for processing the input song(s) from the Webapp side? This way we insure that the mp3 is processed into a spectrogram in the exact same way as the model will expect, and if any modifications are made to those functions, both processes are referencing the same code.

2023-12-20 11:23 UTC, octodoge commented on README.md
No way a simple push can work after a rebase IMO. But as I said I didn't try. Did it ever work for you?
`--force-with-lease` is a safer alternative to `--force`

2023-12-20 11:28 UTC, octodoge commented on data_collection.ipynb
Sure, good point! But maybe is better to merge this branch as it is so Marta can start working. What do you think? I can pop it out in another branch

2023-12-20 13:43 UTC, 15Max approved these changes
I'm going to approve the branch so I can start working on the model, in the meantime Mathias will work on the explanations Madie asked for

2023-12-20 15:05 UTC, octodoge commented
> I'm going to approve the branch so I can start working on the model, in the meantime Mathias will work on the explanations Madie asked for

Not enough to be able to merge but it was worth trying

2023-12-20 15:45 UTC, octodoge commented on README.md
Just tested for completeness. No way:
```
(spectrofy) ┌─[mathias@parrot]─[~/Desktop/Spectrofy]
└──╼ $git push
To github.com:MadelineKelly196/Spectrofy.git
 ! [rejected]        data-collection -> data-collection (non-fast-forward)
error: failed to push some refs to 'github.com:MadelineKelly196/Spectrofy.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
(spectrofy) ┌─[✗]─[mathias@parrot]─[~/Desktop/Spectrofy]
└──╼ $git push --force-with-lease 
Uploading LFS objects: 100% (957/957), 77 MB | 0 B/s, done.                                                                                                
Enumerating objects: 1064, done.
Counting objects: 100% (1064/1064), done.
Delta compression using up to 4 threads
Compressing objects: 100% (1038/1038), done.
Writing objects: 100% (1061/1061), 493.95 KiB | 4.66 MiB/s, done.
Total 1061 (delta 57), reused 31 (delta 22), pack-reused 0
remote: Resolving deltas: 100% (57/57), completed with 2 local objects.
To github.com:MadelineKelly196/Spectrofy.git
 + d7f6786...588f529 data-collection -> data-collection (forced update)
```

2023-12-20 15:53 UTC, octodoge commented on data_collection.ipynb
Definitely gonna create a new branch (from this one since it cannot be merged yet). Makes more sense, without messing up this code

2023-12-20 18:10 UTC, MadelineKelly196 approved these changes
Creating another branch to pop out the mp3 conversion later, so that Marta can work on this version now, sounds good to me. Thanks!

2023-12-20 18:10 UTC, MadelineKelly196 commented on README.md
Ah, I see. Git push worked in my example case, but it was a very simple test case, so perhaps in more complicated situations it doesn't work well. I'm ok to use --force-with-lease in this case, since it also won't affect changes from other authors.

2023-12-20 18:25 UTC, octodoge commented on README.md
`push` shouldn't work in any case actually after a rebase because it changes all the commit of the branch (even if they look the same, they got different date, different hash, etc.). So the local and remote branch diverge. Maybe you didn't actually rebased when you tested (eg. you had no new commit, so the rebase did nothing)

2023-12-20 18:29 UTC, merged